### ISSUE TITLE
No pom.xml file uploaded to Nexus repository

### ISSUE THREAD

**Issue by tgmuender** [sonatype/nxrm3-maven-plugin#19]
When using the plugin with `mvn install nxrm3:staging-deploy -Dtag=1.2.3` I see that the actual artifact (jar file) of my project is uploaded to my Nexus repository. However, the `pom.xml` of my project is missing in the Nexus repository and it looks like it was not uploaded. 

Is this a bug or am I missing something in my configuration (I haven't specified a `packaging` type in my pom)? 

For reference, I'm using the plugin with the following configuration:
```
<plugin>
    <groupId>org.sonatype.plugins</groupId>
    <artifactId>nxrm3-maven-plugin</artifactId>
    <version>1.0.2</version>
    <configuration>
        <nexusUrl>...</nexusUrl>
        <serverId>...</serverId>
        <repository>staging-repo</repository>
        <sourceRepository>source-repo</sourceRepository>
        <destinationRepository>dest-repo</destinationRepository>
    </configuration>
    <executions>
        <execution>
            <id>default-deploy</id>
            <phase>deploy</phase>
            <goals>
                <goal>deploy</goal>
            </goals>
        </execution>
    </executions>
</plugin>
```

**Comment by joedragons** [comment]
@tgmuender I am seeing the same behavior, so I suspect this is either a bug or by design (sorry that's not very helpful).  Do you mind filing an issue in our JIRA (issues.sonatype.com)?  We probably should lock issues down here; that project is what we monitor for bugs.

**Comment by tgmuender** [comment]
@joedragons Thanks for the hint - I set up a ticket in the Sonatype JIRA (https://issues.sonatype.org/browse/NEXUS-20029)
